site_name: "S documentation"
site_url: https://sybdata.github.io/docs
site_favicon: images/favicon.png
copyright: 'Copyright &copy; 2019 S'
repo_name: Sybdata
repo_url: https://sybdata.github.io/docs
edit_uri: ../mailcow-docs/edit/master/docs/
remote_branch: gh-pages
theme: material
markdown_extensions:
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - admonition
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
pages:
- 'Information & Support': 'index.md'
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'indigo'
    accent: 'orange'
  social:
    - type: globe
      link: https://sybdata.github.io/docs
    - type: github-alt
      link: https://sybdata.github.io/docs
extra_css: [extra.css]

